version: "3.9"
services:
  worker:
    build: .
    environment:
      STRING_SESSION: $STRING_SESSION # defaults to None
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      ALIVE_NAME: $ALIVE_NAME # defaults to None
      ENV: $ENV # defaults to None
      COMMAND_HAND_LER: $COMMAND_HAND_LER # defaults to None
      TG_BOT_USERNAME: $TG_BOT_USERNAME # defaults to None
      TG_BOT_TOKEN: $TG_BOT_TOKEN # defaults to None
      TZ: $TZ # defaults to None
      UPSTREAM_REPO: $UPSTREAM_REPO # defaults to None
      
      
